version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGUSER: "${PGUSER:-postgres}"
      PGPASSWORD: "${PGPASSWORD:-password}"
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - "./:/swoop"
    working_dir: "/swoop"
